image: python:3.9

# Define stages
stages:
  - install
  - deploy

# Install dependencies stage
install_dependencies:
  stage: install
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv/

deploy:
  stage: deploy
  script:
    - python example/sdl_example/abstract_sdl.py
  only:
    - main