image: python:3.9  # Specify the Docker image with Python

# Define stages
stages:
  - install
  - deploy

# Install dependencies stage
install_dependencies:
  stage: install
  script:
    - echo "installing"
#    - python -m venv venv  # Create a virtual environment
#    - . venv/bin/activate  # Activate the virtual environment
#    - pip install -r requirements.txt  # Install dependencies from requirements.txt
#    - pip install gunicorn==20.1.0
  artifacts:
    paths:
      - venv/  # Store the virtual environment as an artifact (optional)

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "deploying"
#    - . venv/bin/activate  # Activate the virtual environment
#    - python -m example.sdl_example.abstract_sdl  # Run the script
  only:
    - main