image: python:3.9  # Specify the Docker image with Python

# Define stages
stages:
  - install
  - build
  - deploy

# Install dependencies stage
install_dependencies:
  stage: install
  script:
    - echo "installing"
#    - python -m venv venv  # Create a virtual environment
#    - . venv/bin/activate  # Activate the virtual environment
#    - pip install -r requirements.txt  # Install dependencies from requirements.txt
#    - pip install gunicorn==20.1.0
  artifacts:
    paths:
      - venv/  # Store the virtual environment as an artifact (optional)

# Job to build the package
build_package:
  stage: build
  image: python:3.9
  script:
    - pip install --upgrade pip
    - pip install setuptools wheel twine
    - python setup.py sdist bdist_wheel
  only:
    - tags
  artifacts:
    paths:
      - dist/*

# Job to deploy to PyPI
deploy_pypi:
  stage: deploy
  image: python:3.x  # Same Python version
  script:
    - pip install twine
    - twine upload dist/* -u $PYPI_USERNAME_IVORY -p $PYPI_PASSWORD_IVORY
  only:
    - tags
  dependencies:
    - build_package