stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: python:3.8-slim
  script:
    - pip install -r requirements.txt

test_job:
  stage: test
  image: python:3.8-slim
  script:
    - pytest

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to production server"
  only:
    - main
