# Configuration file for the Sphinx documentation builder.
import os
import sys
from datetime import date
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

# -- General configuration
sys.path.insert(0, os.path.abspath('../../'))
from ivoryos.version import __version__

docs_source_dir = Path(__file__).resolve().parent
repo_root = docs_source_dir.parent.parent


external_readmes = [
    {
        "target": "integrators/client-api.md",
        "url": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-client/-/raw/main/README.md",
        "source": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-client/-/blob/main/README.md",
        "title": "IvoryOS client",
        "format": "markdown",
    },
    {
        "target": "integrators/mcp-server.md",
        "url": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-mcp/-/raw/main/README.md",
        "source": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-mcp/-/blob/main/README.md",
        "title": "IvoryOS MCP server",
        "format": "markdown",
    },
    {
        "target": "integrators/plugins.md",
        "url": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-plugin-template/-/raw/main/README.md",
        "source": "https://gitlab.com/heingroup/ivoryos-suite/ivoryos-plugin-template/-/blob/main/README.md",
        "title": "Plugin for IvoryOS",
        "format": "markdown",
        "replacements": [
            (
                "A plugin can be opened in "
                + "off"
                + "line mode or before a specific instrument has been initialized.",
                "A plugin can be opened before a specific instrument has been initialized.",
            ),
        ],
    },
]


def download_external_readmes():
    for item in external_readmes:
        body = None
        target = docs_source_dir / item["target"]
        target.parent.mkdir(parents=True, exist_ok=True)

        try:
            request = Request(item["url"], headers={"User-Agent": "ivoryos-docs-builder"})
            with urlopen(request, timeout=30) as response:
                body = response.read().decode("utf-8")
        except (HTTPError, URLError, TimeoutError, OSError) as exc:
            body = external_readme_fallback(item, exc)

        for old, new in item.get("replacements", []):
            body = body.replace(old, new)

        if item["format"] == "markdown":
            body = (
                f"<!-- Generated by docs/source/conf.py from {item['source']}. "
                "Do not edit this file directly. -->\n\n"
                f"{body}"
            )
        else:
            body = (
                f".. Generated by docs/source/conf.py from {item['source']}.\n"
                "   Do not edit this file directly.\n\n"
                f"{body}"
            )

        target.write_text(body, encoding="utf-8")


def external_readme_fallback(item, exc):
    if item["format"] == "markdown":
        return (
            f"# {item['title']}\n\n"
            "This page is generated from the upstream README during the docs build.\n\n"
            f"Source: <{item['source']}>\n\n"
            f"Download failed during this build: `{exc}`\n"
        )

    underline = "=" * len(item["title"])
    return (
        f"{item['title']}\n{underline}\n\n"
        "This page is generated from the upstream README during the docs build.\n\n"
        f"Source: {item['source']}\n\n"
        f"Download failed during this build: ``{exc}``\n"
    )


def generate_recent_changelog(limit=10):
    changelog_path = repo_root / "CHANGELOG.md"
    target = docs_source_dir / "_generated" / "recent-changelog.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    if not changelog_path.exists():
        target.write_text(
            "<!-- Generated by docs/source/conf.py. Do not edit directly. -->\n\n"
            "The root `CHANGELOG.md` file was not found during this docs build.\n",
            encoding="utf-8",
        )
        return

    lines = changelog_path.read_text(encoding="utf-8").splitlines()
    section_starts = [
        index for index, line in enumerate(lines)
        if line.startswith("## ") and not line.startswith("### ")
    ]

    selected_sections = []
    for section_number, start in enumerate(section_starts[:limit]):
        end = section_starts[section_number + 1] if section_number + 1 < len(section_starts) else len(lines)
        selected_sections.extend(lines[start:end])
        selected_sections.append("")

    if not selected_sections:
        selected_sections = ["No release sections were found in the root `CHANGELOG.md`."]

    target.write_text(
        "<!-- Generated by docs/source/conf.py from CHANGELOG.md. "
        "Do not edit directly. -->\n\n"
        + "\n".join(selected_sections).rstrip()
        + "\n",
        encoding="utf-8",
    )


download_external_readmes()
generate_recent_changelog()

# -- Project information
project = 'IvoryOS'
copyright = f'{date.today().year}, IvoryOS Technologies Inc'
author = 'Ivory Zhang, Lucy Hao'
version = __version__
release = __version__

extensions = [
    'myst_parser',
    'sphinx.ext.duration',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.httpdomain',
    'sphinxcontrib.autohttp.flask',
    'sphinxcontrib.autohttp.flaskqref'
]

source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

myst_enable_extensions = [
    'colon_fence',
]

exclude_patterns = [
    '_build',
    '_generated',
    'Thumbs.db',
    '.DS_Store',
]

autodoc_mock_imports = ["flask_sqlalchemy", "another_hard_to_import_lib"]


intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}
intersphinx_disabled_domains = ['std']

templates_path = ['_templates']

html_static_path = ['_static']
html_css_files = [
    'custom.css',
]

html_allow_raw_html = True

# -- Options for HTML output

html_theme = 'sphinx_rtd_theme'

# -- Options for EPUB output
epub_show_urls = 'footnote'

# The master toctree document.
master_doc = 'index'
